use EMP;

CREATE TABLE EQUIPAMENTO (
   EQNO INT,
   ENOME VARCHAR(30),
   DNO INT,
   PRIMARY KEY (EQNO),
   FOREIGN KEY (DNO) REFERENCES DEPARTAMENTO (DNUMERO) ON UPDATE CASCADE
);

INSERT INTO DEPARTAMENTO VALUES ("Novo", 2, "987654321", "1980-12-12");

INSERT INTO EQUIPAMENTO VALUES (1,"Computador", 2);
INSERT INTO EQUIPAMENTO VALUES (2,"Computador", 2);
INSERT INTO EQUIPAMENTO VALUES (3,"Fax", 2);
INSERT INTO EQUIPAMENTO VALUES (4,"Computador", 4);
INSERT INTO EQUIPAMENTO VALUES (5,"Computador", 4);